---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-volume-db1"
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path:  /run/desktop/mnt/host/c/Users/lmart/storage/db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - lgpddev
                - docker-desktop
