---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pontus-extract-totvs-claim0
  name: pontus-extract-totvs-claim0
spec:
  volumeName: pv-volume-extract
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
status: {}
