apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-volume-db"
  labels:
    type: local
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: /home/lgpddev/storage/db
  persistentVolumeReclaimPolicy: Recycle
