---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-volume-extract-sharepoint-data-breaches"
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Mi
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: {{ .Values.pvvals.storagePath }}/extract/sharepoint/data-breaches
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pontus-extract-sharepoint-data-breaches-pv-claim0
  name: pontus-extract-sharepoint-data-breaches-pv-claim0
spec:
  storageClassName: local-path
  volumeName: pv-volume-extract-sharepoint-data-breaches
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
status: {}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pv-extract-sharepoint-data-breaches
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          name: pv-extract-sharepoint-data-breaches
          labels:
            io.kompose.network/pontusvision: "true"
            io.kompose.service: pv-extract-sharepoint-data-breaches
        spec:
          containers:
          - name: pv-extract-lambdas
            image: pontusvisiongdpr/pv-extract-wrapper:1.13.2
            env:
            - name: PV_TIMEOUT_MS
              value: "1500000"
            - name: PV_GRAPHDB_URL_PREFIX
              value: http://graphdb-nifi:3001
            - name: PV_OFFICE_365_ONPREM_CREDS_FILE
              value: "/run/secrets/sharepoint-json"
            - name: PV_GRAPHDB_INPUT_JSONPATH
              value: "$.queryResp[*].fields"
            - name: PV_STATE_FILE
              value: "/mnt/pv-extract-lambda/state.json"
            - name: PV_GRAPHDB_INPUT_RULE
              value: "sharepoint_data_breaches"
            - name: PV_SHAREPOINT_SITE_ID
              value: "sunnyvalecombr.sharepoint.com,fd97ef96-8dc8-41f2-b2c9-d2b058c33118,f40ffdd1-c535-4212-b345-19f42f764383"
            - name: PV_SHAREPOINT_LIST_ID
              value: "e6d9052a-c5ea-4c55-88e7-24d8bc9d0143"
              #value: "b4271624-5a7b-441e-a019-8b87313a7bf4"
            imagePullPolicy: Always
            command:
            - /usr/bin/node 
            - dist/office365/sharepoint/app.js
            volumeMounts:
            - mountPath: "/run/secrets/sharepoint-json"
              subPath: sharepoint-json
              name: sharepoint-json
            - mountPath: "/mnt/pv-extract-lambda/"
              name: pontus-extract-sharepoint-data-breaches-pv-claim0
          volumes:
          - name: sharepoint-json
            secret:
              secretName: sharepoint-json
          - name: pontus-extract-sharepoint-data-breaches-pv-claim0
            persistentVolumeClaim:
              claimName: pontus-extract-sharepoint-data-breaches-pv-claim0

          restartPolicy: OnFailure
          #£concurrencyPolicy: Forbid
