---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pontus-extract-protheus-pv-claim0
  name: pontus-extract-protheus-pv-claim0
spec:
  storageClassName: local-path
  volumeName: pv-volume-extract-protheus
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-volume-extract-protheus"
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Mi
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: {{ .Values.pvvals.storagePath }}/extract/protheus
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pv-extract-protheus-sa1-cliente
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          name: pv-extract-protheus-sa1-cliente
          labels:
            io.kompose.network/pontusvision: "true"
            io.kompose.service: pv-extract-protheus-sa1-cliente
        spec:
          containers:
          - name: pv-extract-lambdas
            image: pontusvisiongdpr/pv-extract-wrapper:1.13.2
            env:
            # TODO: REMOVE THIS AS SOON AS sv-card-165 is resolved (https://trello.com/c/m7z2LBDl)
            #- name: NODE_TLS_REJECT_UNAUTHORIZED
            #value: "0"
            - name: PV_TIMEOUT_MS
              value: "1500000"
            - name: PV_GRAPHDB_URL_PREFIX
              value: http://graphdb-nifi:3001
            - name: PV_SECRET_MANAGER_ID
              value: "/run/secrets/totvs-json"
            - name: PV_SECRET_COMPONENT_NAME
              value: "totvs"
            - name: PV_REQUEST_URL
              #value: "https://protheus-ws.sunnyvale.com.br:8009/pontusvision/pontusvision-lgpd-totvs-proteus/1.0.0/sa1_cliente/objs"
              value: "{{ .Values.pvvals.protheusUrlPrefix }}/sa1_cliente/objs"
            - name: PV_STATE_FILE
              value: "/mnt/pv-extract-state/totvs-state-sa1-cliente.json"
            - name: PV_GRAPHDB_INPUT_RULE
              value: "totvs_protheus_sa1_clientes"
            - name: PV_DEBUG
              value: "true"

            imagePullPolicy: Always
            command:
            - /usr/bin/node 
            - dist/rest-handler/totvs/app.js
            volumeMounts:
            - mountPath: "/run/secrets/totvs-json"
              subPath: totvs-json
              name: totvs-json
            - mountPath: "/mnt/pv-extract-state/"
              name: pontus-extract-protheus-pv-claim0
          volumes:
          - name: totvs-json
            secret:
              secretName: totvs-json
          - name: pontus-extract-protheus-pv-claim0
            persistentVolumeClaim:
              claimName: pontus-extract-protheus-pv-claim0

          restartPolicy: OnFailure
          #£concurrencyPolicy: Forbid
