---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-volume-extract-ploomes"
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 10Mi
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: {{ .Values.pvvals.storagePath }}/extract/ploomes
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pontus-extract-ploomes-claim0
  name: pontus-extract-ploomes-claim0
spec:
  storageClassName: local-path
  volumeName: pv-volume-extract-ploomes
  #storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
status: {}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pv-extract-ploomes
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          name: pv-extract-ploomes
          labels:
            io.kompose.network/pontusvision: "true"
            io.kompose.service: pv-extract-ploomes
        spec:
          containers:
          - name: pv-extract-ploomes
            image: pontusvisiongdpr/pv-extract-wrapper:1.13.2
            env:
            - name: PV_TIMEOUT_MS
              value: "15000"
            - name: PV_GRAPHDB_URL_PREFIX
              value: http://graphdb-nifi:3001
            - name: PV_SECRET_MANAGER_ID
              value: "/run/secrets/ploomes-json"
            - name: PV_SECRET_COMPONENT_NAME
              value: "ploomes"
            - name: PV_REQUEST_URL
              value: "https://api2.ploomes.com/Contacts"
            - name: PV_STATE_FILE
              value: "/mnt/pv-extract-state/ploomes-state.json"
            - name: PV_REST_HANDLER_EXTRA_QUERY_PARAMS
              value: '{ "$expand": "City,State,Country" }'
            - name: PV_DEBUG
              value: 'true'

            imagePullPolicy: Always
            command:
            - /usr/bin/node 
            - dist/rest-handler/ploomes/app.js
            volumeMounts:
            - mountPath: "/run/secrets/ploomes-json"
              subPath: ploomes-json
              name: ploomes-json
            - mountPath: "/mnt/pv-extract-state/"
              name: pontus-extract-ploomes-claim0
          volumes:
          - name: ploomes-json
            secret:
              secretName: ploomes-json
          - name: pontus-extract-ploomes-claim0
            persistentVolumeClaim:
              claimName: pontus-extract-ploomes-claim0

          restartPolicy: OnFailure
          #£concurrencyPolicy: Forbid
