---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pontus-track-claim0
  name: pontus-track-claim0
spec:
  volumeName: pv-volume-db1
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
#  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set

status: {}
