---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pontus-nifi-claim0
  name: pontus-nifi-claim0
spec:
  volumeName: pv-volume-nifi
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
status: {}
