---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/pontusvision: "true"
    io.kompose.service: pontus-gdpr
  name: pontus-gdpr
spec:
  containers:
  - args:
    - /bin/bash
    - -c
    - |2
         getent hosts pontus-formio.pontus-demo-com
         getent hosts pontus-comply-keycloak.pontus-demo-com
         getent hosts pontus-comply-keycloak
         nginx -g 'daemon off;'
    image: pontusvisiongdpr/pontus-comply-nginx-gdpr:light
    name: pontus-gdpr
    ports:
    - containerPort: 18443
    resources: {}
    securityContext:
      privileged: true
  hostname: pontus-gdpr
  restartPolicy: OnFailure
  subdomain: pontus-demo-com
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f gdpr-odb-grafana-latest.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: pontus-gdpr
  name: pontus-gdpr
spec:
  ports:
  - name: "18443"
    port: 18443
    targetPort: 18443
  selector:
    io.kompose.service: pontus-gdpr
  type: LoadBalancer
status:
  loadBalancer: {}
