# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pvvals:
  imageVers:
    graphdb: "pontusvisiongdpr/pontus-track-graphdb-odb-pt:1.15.1"
    grafana: "pontusvisiongdpr/grafana-pt:1.13.2"
  storagePath: "/home/$HOSTNAME/storage"
  hostname: "$HOSTNAME"  
  APIUrlPrefix: "https://api"
  # Add as many vars as needed
  # to get the keycloak public key, do an HTTP GET to the following URL: https://<hostname>/auth/realms/pontus
  keycloakPubKey: "**************************************************************" 
  
